apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fastmcp
  description: 'A Onboard an Existing Repo to Backstage created via Backstage'
  annotations:
    repo: patterninc/fastmcp
  labels:
    CostCenter: AIPLATFORM
    Environment: stage
    Name: fastmcp
    Owner: ai-infra-comms
    Department: AIPLATFORM
    CreatedBy: Backstage
spec:
  type: service
  system: aiplatform
